B4 Project's folder name changed
htw-imi-showtime/showtime-website pull request #73
Opened 2021-02-08 17:38 UTC by mbareeva

2021-02-08 22:32 UTC, bkleinen requested changes
please don't change the showtime theme.

2021-02-08 22:43 UTC, bkleinen commented
@Kaes3kuch3n : es sind einige große SVGs drin, evtl. gehen die kleiner? Könnten Sie da mal reingucken bitte?

2021-02-09 12:59 UTC, Kaes3kuch3n commented
> @Kaes3kuch3n : es sind einige große SVGs drin, evtl. gehen die kleiner? Könnten Sie da mal reingucken bitte?

@bkleinen Bei mir sind die SVGs alle kleiner als 500KB. Sollen sie noch kleiner werden?

2021-02-09 18:37 UTC, mbareeva commented
@bkleinen We have reverted the changes from the file themes/showtime-theme-2021 from last commit. Hope it is what you asked us for. Thank you.

2021-02-09 23:08 UTC, merged